name: Update BAMIS WRF Forecast

on:

  # Every day at 08:00 Bangladesh time
  # Bangladesh = UTC + 6
  # 08:00 BDT = 02:00 UTC

  schedule:
    - cron: "0 2 * * *"

  # Manual run
  workflow_dispatch:


jobs:

  update-bamis-wrf:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # Install system dependencies (needed for some R packages)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      # Install + cache R packages (FAST 🚀)
      - name: Setup dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rvest
            dplyr
            stringr
            lubridate
            googlesheets4
          extra-repositories: https://packagemanager.posit.co/cran/latest

      # ------------------------------------------------------
      # RUN SCRAPER
      # ------------------------------------------------------

      - name: Run BAMIS WRF scraper

        env:

          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GSHEET_JSON }}

        run: |

          Rscript weather_daily_forecast_bamis.R
